# ejerciciodeclase01-DiazCode404
ejerciciodeclase01-DiazCode404 created by GitHub Classroom


En estos ejercicios aprendemos sobre el manejo de errores usando la declaracion try-catch.
Cada vez que se produce una excepcion o error imprevisto dentro del bloque try (por ejemplo el ingreso de un caracter no deseado, un error aritmetico, etc)
este error es tomado por el bloque catch para mostrar, o no, un mensaje describiendo el error en nuestro codigo y evitando que el programa se "rompa". En otras palabras,
dentro del bloque try debe ir aquella porcion de codigo que probablemente pueda tener algun tipo de error; En caso de que exista dicho error, en el bloque catch se
debe instanciar una variable de tipo Exception (u otro tipo de excepcion) y mostrar el error.
